config/routes.rb
Rails.application.routes.draw do

  
  root 'groups#index'

  resources :groups do # 巢狀機制
    resources :posts
  end

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :title, presence: true

	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :group
	validates :content, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups=Group.all
	end

	def new
		@group= Group.new
	end

	def show
		@group=Group.find(params[:id])
		@posts = @group.posts
	end

	def edit
		@group=Group.find(params[:id])
	end

	# 新增submit後,將表單送出的訊息,存入db
	def create
		@group=Group.new(group_params)

		if @group.save
			redirect_to groups_path
		else
			render :new
		end
	end

	def update
		@group = Group.find(params[:id])

		if @group.update(group_params)
			redirect_to groups_path, notice: "修改討論版成功"
		else
			render :edit
		end
	end

	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to groups_path, alert: "討論板已刪除"
	end

	private

	def group_params
		params.require(:group).permit(:title, :description)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_group


	def new
		# @group = Group.find(params[:group_id])
		@post = @group.posts.new
	end

	# edit action
	def edit
		# @group = Group.find(params[:group_id])
		@post = @group.posts.find(params[:id])
	end

	def create
		# @group = Group.find(params[:group_id])
		@post = @group.posts.build(post_params)

		if @post.save
			redirect_to group_path(@group), notice: "新增文章成功！"
		else
			render :new
		end
	end

	def update
		# @group = Group.find(params[:group_id])
		@post =@group.posts.find(params[:id])

		if @post.update(post_params)
			redirect_to group_path(@group), notice: "文章修改成功"
		else
			render :edit
		end
	end

	def destroy
		# @group = Group.find(params[:group_id])
		@post = @group.posts.find(params[:id])

		@post.destroy
		redirect_to group_path(@group), alert: "文章已刪除"
	end

	private

	# before_action
	def find_group
		@group = Group.find(params[:group_id])
	end

	def post_params
		params.require(:post).permit(:content)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	# 測試notice_message :notice, :alert, :warning
	def index
		# flash[:notice]='早安！你好！'
		# flash[:alert]='晚安！該睡了！'
		flash[:warning]='這是warning訊息'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def notice_message
		alert_types= { notice: :success, alert: :danger }

		close_button_options= { class: 'close', 
								'data-dismiss' => 'alert', 'aria-hidden' => true}
		close_button= content_tag(:button, 'x', close_button_options)

		alerts= flash.map do |type, message|
			alert_content= close_button + message

			alert_type= alert_types[type.to_sym] || type
			alert_class= "alert alert-#{alert_type} alert-dismissable"

			content_tag(:div, alert_content, class: alert_class)
		end

		alerts.join('\n').html_safe
	end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_footer.html.erb
<footer class='container' style='margin-top: 100px;'>
	<p class="text-center">Copyright ©2016 Rails101
		<br>Design by <a href="courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
	</p>
</footer>

app/views/common/_navbar.html.erb
<nav class='navbar navbar-default' role='navigation'>
	<div class="container-fluid">
		<!-- brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<a class="navbar-brand" href="/">Rails 101</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id='bs-example-navbar-collapse-1'>
			<ul class="nav navbar-nav navbar-right">
				
				<% if !current_user %>
					<li> <%= link_to("註冊", new_user_registration_path) %> </li>

					<li> <%= link_to('登入', new_user_session_path) %></li>
				<% else %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Hi!, <%= current_user.email %>
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
						</ul>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/groups/edit.html.erb
<div class="col-md4 col-md-offset-4">
	<h1>修改討論版</h1>

	<hr>
	<%= simple_form_for @group do |f| %>
		<div class="form-group">
			<%= f.input :title %>
			<%= f.input :description %>
		</div>
		<%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..."} %>
	<% end %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
	<div class="group">
		<%= link_to("New group", new_group_path, class: 'brn btn-primary pull-right') %>
	</div>
	<table class="table table-hover">
		<thead>
			<tr>
				<td>#</td>
				<td>Title</td>
				<td>Description</td>
			</tr>
		</thead>
		<tbody>
			<% @groups.each do |group| %>
				<tr>
					<td>#</td>
					<td><%= link_to(group.title, group_path(group)) %></td>
					<td><%= group.description %></td>
					<td>
						<%= link_to('Edit', edit_group_path(group), class: 'btn btn-sm btn-default') %>
						<%= link_to('Delete', group_path(group), class: 'btn btn-sm btn-default',
										method: :delete, data:{ confirm: 'Are you sure?' }) %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<h1>新增討論版</h1>

	<hr>
	<%= simple_form_for @group do |f| %>
		<div class="form-group">
			<%= f.input :title, input_html: { class: "form-control"} %>
			<%= f.input :description, input_html: { class: "form-control"} %>

		</div>
		<%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..."} %>
	<% end %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
	<div class="group">
		<!-- 新增table顯示group下的posts -->
		<%= link_to("New Post", new_group_post_path(@group), class: "btn btn-warning pull-right") %>
		<%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right") %>
	</div>
	<h2><%= @group.title %></h2>
	<p><%= @group.description %></p>

	<!-- 新增table顯示group下的posts -->
	<table class="table">
		<thead>
			<tr>
				<th>文章</th>
				<th colspan="2"></th>
			</tr>
		</thead>
		<tbody>
			<% @posts.each do |post| %>
				<tr>
					<td><%= post.content %></td>
					<td>
						<%= link_to("Edit", edit_group_post_path(post.group, post), class: "btn btn-default btn-xs")%>
						<%= link_to("Delete", group_post_path(post.group, post), class: "btn btn-default btn-xs", method: :delete, data: { confirm: "Are you sure?"})%>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- 修改 -->
	<div class="container-fluid">
		<%= render 'common/navbar' %>
		<!-- 把notice_message放進layouts html-->
		<%= notice_message %>
		<%= yield %>
	</div>

	<%= render 'common/footer' %>

</body>
</html>

app/views/posts/edit.html.erb
<h1 class="text-center">修改文章</h1>

<div class="col-md-4 col-md-offset-4">
	<%= simple_form_for [@group,@post] do |f| %>
		<div class="form-group">
			<%= f.input :content, input_html: { class: "form-control"} %>
		</div>
		<div class="form-actions">
			<%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary"%>
		</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center">新增文章</h1>

<div class="co-md-4 col-md-offset-4">
	<%= simple_form_for [@group,@post] do |f| %>
		<div class="form-group">
			<%= f.input :content, input_html: { class: "form-control"} %>
		</div>
		<div class="form-actions">
			<%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary"%>
		</div>
	<% end %>
</div>

app/views/welcome/index.html.erb
<h1> helloWorld!</h1>